## Numpy Arrays

In [5]:
list = [1,2,3,4,5]

In [6]:
list

[1, 2, 3, 4, 5]

In [7]:
import numpy as np
arr = np.array(list)

In [9]:
arr

array([1, 2, 3, 4, 5])

In [10]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
np.arange(0,10,0.5) # first argument included, last not included

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.linspace(1,10,10) # contains both first and second argument
# third argument: total number of points in the interval

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [36]:
np.linspace(1,10,19) # 3rd arg arange: step-size vs linspace: number of points

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [39]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random

In [42]:
np.random.rand(5) # from uniform [0,1)

array([0.79121834, 0.18750829, 0.82891723, 0.16595977, 0.50717859])

In [43]:
np.random.rand(2,5) # do not pass a tuple in this method

array([[0.46945646, 0.52817768, 0.40680035, 0.87748358, 0.31532131],
       [0.80944733, 0.72747175, 0.4569266 , 0.60294246, 0.91025882]])

In [46]:
np.random.randn(4,5) # from normal

array([[-0.91065122,  0.6325207 ,  0.43976909, -0.33684114, -1.26942938],
       [-0.52758683, -1.18004896,  0.40446335,  0.67368795, -0.79815026],
       [ 0.20711077,  0.55446262, -0.3994235 ,  1.51132284,  0.70649542],
       [-0.5569919 ,  0.2253579 ,  0.33167523,  0.64436361, -0.07011135]])

In [53]:
np.random.randint(1,101,(4,6)) # low inclusive, high exclusive

array([[27, 96, 65, 77, 58,  1],
       [53, 51, 57, 64, 54, 38],
       [48, 86, 68, 81, 59, 90],
       [59, 64, 34, 96, 98, 18]])

## Array Attributes and Methods

In [87]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [88]:
ranarr = np.random.randint(0,50,10)
ranarr

array([11,  1,  0,  0, 34, 24, 18, 36,  1,  9])

In [57]:
arr.reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
ranarr.reshape((2,5))

array([[38, 48, 28, 26,  9],
       [23, 12, 41, 15, 26]])

In [62]:
ranarr.max()

48

In [66]:
ranarr.argmax()

1

In [67]:
ranarr.argmin()

4

In [89]:
arr.shape # NO BRACKETS!

(25,)

In [91]:
arr.reshape((5,5)).shape

(5, 5)

In [92]:
arr.dtype # data type

dtype('int32')

In [93]:
from numpy.random import randint

In [95]:
randint(0,100,15) # without writing np.random...

array([ 3, 94, 99, 76,  4, 15, 97, 68, 90, 10, 24, 35, 48, 19, 52])