## Numpy Indexing and Selection

In [2]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[5:8]

array([5, 6, 7])

In [9]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [10]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [13]:
arr[0:5] = 100 # broadcasting
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [19]:
arr = np.arange(0,11)
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [22]:
slice_of_arr[:] = 99

In [23]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [24]:
arr # IMPORTANT! arr is also changed! It is copied by reference!

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

When __slicing__: to avoid this (copying by reference), use .copy() method (copying by value)

In [26]:
arr = np.arange(0,11)
slice_of_arr = arr[0:6].copy()
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [30]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,30,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 30, 45]])

In [35]:
arr_2d[0] # whole row

array([ 5, 10, 15])

In [37]:
arr_2d[0][1] # row, column

10

Choosing elements: `arr[a,b]` but also `arr[a][b]`

In [39]:
arr_2d[0,1] # also with ,

10

In [43]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 30, 45]])

In [45]:
arr_2d[0:2,1:3]

array([[10, 15],
       [25, 30]])

In [46]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [48]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
bool_arr = arr > 5

In [55]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

__Conditional selection__. Really helpful.

In [57]:
arr[arr > 5] # conditional selection

array([ 6,  7,  8,  9, 10])

In [59]:
arr[arr < 3]

array([1, 2])