# NumPy Operations

In [3]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [12]:
arr - 5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [13]:
arr / arr

C:\Users\fotis\AppData\Local\Temp/ipykernel_26188/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [15]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [16]:
np.sqrt(arr) # broadcasting

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [17]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [18]:
np.max(arr)

10

In [19]:
np.argmax(arr)

10

In [20]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [21]:
np.log(arr)

C:\Users\fotis\AppData\Local\Temp/ipykernel_26188/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [24]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,2],[3,2]])

In [27]:
a

array([[1, 2],
       [3, 4]])

In [28]:
b

array([[2, 2],
       [3, 2]])

In [25]:
a * b

array([[2, 4],
       [9, 8]])

In [26]:
a @ b

array([[ 8,  6],
       [18, 14]])